# Site
repository: asuleyman
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aziza Suleymanzade
title: Physicist
email: azizas@uchicago.edu
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: AzizaS
github_username:  AzizaSuleyman
linkedin_username: aziza-suleymanzade-00b21076
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-7N3C97D3RQ"
# google_analytics: ""

# About Section
about_title: About Me
about_profile_image: images/profile1.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Aziza and I’m a Postdoctoral Fellow at Harvard University in Quantum Information Science. I am interested in building hybrid quantum 
  systems working on building quantum networks with Silicon Vacancy Centers in diamond nanophotonic cavities. 
  I am generally interested in creating hybrid quantum systems with light using cavity and circuit QED tools. 
  Some of my previous work was on creating nonlinear photonic systems using Rydberg atoms, superconducting circuits in the millimeter-wave band,
   and optical cavities.
content:
  - title: Highlight # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: PhD thesis
        link: "https://simonlab.uchicago.edu/theses/SuleymanzadeAziza_PhDThesis.pdf"
        link_text: "Title: Millimeter wave photons for hybrid quantum systems."          
        quote: > 
          Here, I discuss our work on building a hybrid quantum system for entangling and interconverting single optical and millimeter wave photons using Rydberg atoms as mediators. In addition, I describe our efforts in developing quantum technology in the millimeter wave frequency band and its potential benefits for a wide range of applications.  
                
        description: | # this will include new lines to allow paragraphs
        
          <video src="https://github.com/AzizaSuleyman/azizasuleyman.github.io/raw/main/videos/NonlinearCartoonFull.mp4" controls="controls" style="max-width: 768px;" class = 'center'></video> 
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2009 - 2013
        sub_title: AB Physics
        description: |
          Particle physics phenomena at the LCH, ATLAS experiment \
          <a href="https://lppc.physics.harvard.edu" target="_blank"> Melissa Franklin's Group </a>

      - layout: left
        title: University of Cambridge
        caption: 2013 - 2014
        sub_title: MPhil Physics
        description: |
          Bose Eistein Condensates of 39K atoms with interactions in a uniform box potential. \
          <a href="http://simonlab.uchicago.edu/theses/SuleymanzadeAziza_MasterThesis.pdf" target="_blank"> Thesis PDF: </a> "Ultracold atoms experiment for trapping 39K in an optical box trap." \
          <a href="http://www-amop.phy.cam.ac.uk/amop-zh/" target="_blank"> Hadzibabic Group </a>
          

      - layout: left
        title: University of Chicago
        caption: 2014 - 2021
        sub_title: PhD Physics
        description: |
          Entangling and interconverting single optical and mm-wave photons using Rydberg atoms. MM-wave quantum technology \
          <a href="http://simonlab.uchicago.edu/theses/SuleymanzadeAziza_PhDThesis.pdf" target="_blank"> Thesis PDF: </a> "Millimeter wave photons for hybrid quantum systems." \
          <a href="http://simonlab.uchicago.edu/" target="_blank"> Simon Lab </a> and <a href="http://schusterlab.uchicago.edu" target="_blank"> Schuster Lab </a>  
          
          

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in physics some of my other interests and hobbies are:
      - Science Animation


# Footer
footer_show_references: true

# Build settings
remote_theme: azizasuleyman
#remote_theme: azizasuleyman/modern-resume-theme
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
