# Site settings
site: SuleymanzadeLab
title: SuleymanzadeLab
description: Your site description # Add a description here
url: https://azizasuleyman.github.io/
baseurl: ""

# GitHub Metadata settings
repository: azizasuleyman/azizasuleyman.github.io

# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
    type: "post"

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 

# Sass settings
sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
