# Site
repository: asuleyman
#azizasuleyman/modern-resume-theme
#sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aziza Suleymanzade
title: Physicist
email: azizas@uchicago.edu
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: AzizaS
#github_username:  AzizaSuleyman
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: aziza-suleymanzade-00b21076
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile1.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Aziza, and I’m a Postdoctoral Fellow at Harvard University working on quantum science with Silicon Vacancy Centers in diamonds. I build hybrid quantum systems made of light using cavity and circuit QED platforms. Some of my previous work was on synthesizing nonlinear photonic systems using Rydberg atoms, superconducting circuits in the millimeter-wave band, and optical cavities.
content:
  - title: Highlight # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: PhD thesis
        link: "http://simonlab.uchicago.edu/theses/SuleymanzadeAziza_PhDThesis.pdf"
        link_text: "Title: Millimeter wave photons for hybrid quantum systems."          
        quote: > 
          Here, I discuss our work on building a hybrid quantum system for entangling and interconverting single optical and millimeter wave photons using Rydberg atoms as mediators. In addition, I describe our efforts in developing quantum technology in the millimeter wave frequency band and its potential benefits for a wide range of applications.  
                
        description: | # this will include new lines to allow paragraphs
        
          <video src="https://github.com/AzizaSuleyman/azizasuleyman.github.io/raw/main/videos/NonlinearCartoonFull.mp4" controls="controls" style="max-width: 768px;" class = 'center'></video> 
        
          "Blender animation of an experimental sequence inside of our cryogenic chamber"
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2009 - 2013
        sub_title: AB Physics
        quote: > 
          
        description: |
          "Research: particle physics phenomena at the LCH, ATLAS experiment"
          
      - layout: left
        title: University of Cambridge
        caption: 2013 - 2014
        sub_title: MPhil Physics
        quote: >
        description: |
          "Research: Bose Eistein Condensates of 39K atoms with interactions in a uniform box potential" 
          "Ultracold atoms experiment for trapping 39K in an optical box trap." 
          <a href="http://simonlab.uchicago.edu/theses/SuleymanzadeAziza_MasterThesis.pdf" target="_blank"> Thesis PDF </a>

      - layout: left
        title: University of Chicago
        caption: 2014 - 2021
        sub_title: PhD Physics
        quote: >
          "Research: entangling and interconverting single optical and mm-wave photons using Rydberg atoms. MM-wave quantum technology" 
        description: |
          "Research: entangling and interconverting single optical and mm-wave photons using Rydberg atoms. MM-wave quantum technology" 
          "Millimeter wave photons for hybrid quantum systems."
          <a href="http://simonlab.uchicago.edu/theses/SuleymanzadeAziza_PhDThesis.pdf" target="_blank"> Thesis PDF </a>
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in physics some of my other interests and hobbies are:
      - Science Animation
      - Ballroom Dancing

# Footer
footer_show_references: true
#references_title: References on request (Override references text)

# Build settings
remote_theme: azizasuleyman
#remote_theme: azizasuleyman/modern-resume-theme
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
