- name: Setup Ruby
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: '3.1'

   - name: Update Bundler
     run: gem install bundler

   - name: Bundle Install
     run: |
       bundle config set --local path 'vendor/bundle'
       bundle install

   - name: Update Gemfile.lock
     run: bundle lock --update

   - name: Commit updated Gemfile.lock
     run: |
       git config --global user.name 'GitHub Action'
       git config --global user.email 'action@github.com'
       git add Gemfile.lock
       git commit -m "Update Gemfile.lock" || echo "No changes to commit"
       git push
